### ISSUE TITLE
Use another provider for image generation to reduce costs?

### ISSUE THREAD

**Issue by hola-ivan** [ValeriiZhyla/anki-cards-ai-generator#1]
Given DALLE is aprox 0.04USD/image , would it be possible to consider implementing alternative APIs (Replicate,  fal.ai etc.) where image generation cost is a fraction of DALLE's?

**Comment by ValeriiZhyla** [comment]
Hi,
yes, such change schould be not very challenging.
I'll try different models soon (probably this weekend), and if they perform well on this task - I'll integrate it in the tool.

**Comment by ValeriiZhyla** [comment]
I liked the concept and pricing of Replicate. Now the tool has separate modes for Replicate and OpenAi for image generation.

For Replicate, new options with mode, token, and model url should be set. I tested it with several cheaper models and got actually adequate and stable results.

**Comment by hola-ivan** [comment]
Thank you! I am playing with it and results look great.

I am trying to implement fal.ai 's fal-ai/fast-lightning-sdxl where output is ~$ 0.00041 / image , bringing the cost to generate a 100 card deck to around 10 cents (incl. text and voice) - with potential to reduce text and voice and text as well.

Pls let me know if you are interested in developing the project further, happy to collaborate!

**Comment by ValeriiZhyla** [comment]
Yes, that sounds interesting!

I had an idea to extend the tool to other languages (with good ChatGPT support), e.g. French, Spanish, and Italian.

I have also considered a web interface for this tool as a full-stack pet project, to host it somewhere and avoid local installation. The nasty part is importing decks in Anki via the web - AnkiWeb does not have any usable API. Generating an importable .apkg file with a deck could be a workaround.

I am not sure whether cheap deck generation is a really efficient way to create decks, but surely only a monetizable way. An alternative could be a downloadable open-source collection (in some form, as a service or just as repo) that could be extended with new decks or cards to avoid frequent card regeneration for popular words and phrases.

**Comment by hola-ivan** [comment]
would an anki add on be a feasible option? For instance: Each user provides existing input (language, level, wordlist) and brings their API keys for the AI-related tasks (or ideally runs the AI workflow locally if the hardware/models allow?) and receives the .apkg as an output.

I have also experimented with alternative input sources, i.e. using youtube videos as input (word lists and context are created automatically), as feedback I received was around: "I don't know which words to input". But there is already an existing [solution](https://anki-decks.com/) that essentially does that.

Regarding the card regeneration, I believe https://ankiweb.net/shared/decks already does a good enough job to provide community-ranked listing for "generic basic" decks. I support the idea of enabling users to get their custom decks, because after all, every person's needs/interests will be different (even if that implies frequent card generation for popular words).

**Comment by hola-ivan** [comment]
This deck is output from the fork I created :)

https://ankiweb.net/shared/info/510925137

**Comment by ValeriiZhyla** [comment]
I like your results, images are pretty good :)

would an anki add on be a feasible option? => Afaik, the add-on Anki Connect is currenly an only option for full automation, but import of apkg deck should also work. It is probably feasible to create an add-on, which will utilize the capabilities of Anki Connect locally.

Anki addons require Python GUI, and I don't really enjoy them (and UX would probably be a mess).
I would rather write a standalone web GUI hosted locally which would communicate with local backend server, which would communicate with Anki Connect locally. But it is also a bit messy.

Therefore, I would probably go for normal web-app which generates importable decks, and also manages payments for Replica runs. But you can see, how quickly such a simple tool could become a heavy web monster...
